# Generated by Django 3.1.4 on 2021-01-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210121_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
