# Generated by Django 3.1.4 on 2021-01-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210124_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='identification',
            field=models.TextField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user_default.png', null=True, upload_to=''),
        ),
    ]
