# Generated by Django 3.1.4 on 2021-01-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210104_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='description',
            new_name='description_text',
        ),
    ]
