# Generated by Django 3.1.4 on 2021-01-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210104_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description_text',
            field=models.CharField(max_length=500),
        ),
    ]
