# Generated by Django 3.1.4 on 2021-01-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210104_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description_text',
            field=models.TextField(verbose_name='brief description'),
        ),
    ]
